// Generated by CoffeeScript 1.6.3
var app, express, nconf, proxy_port, _;

express = require('express');

nconf = require('nconf');

_ = require('underscore');

require('sugar');

app = module.exports = express();

app.configure(function() {
  nconf.argv().env();
  nconf.add('default-file', {
    type: 'file',
    file: "config.json"
  });
  console.log(nconf.get("airbnb:host"));
  return console.log(nconf.get("proxy:port"));
});

proxy_port = nconf.get("proxy:port");

app.listen(proxy_port);

console.log('Listening on port:' + proxy_port);

app.get('/hello.txt', function(req, res) {
  return res.send('Hello World');
});

app.get('/user/:id', function(req, res) {
  return res.send("Hello User:" + req.params.id);
});

app.get('/listing/:id', function(req, res) {
  return res.send("Hello Listing:" + req.params.id);
});

app.get('/search/:location', function(req, res) {
  return res.send('Searching in:' + req.params.location);
});
