// Generated by CoffeeScript 1.6.3
var app, express;

express = require('express');

app = module.exports = express();

app.listen(4000);

console.log('Listening on port 4000');

app.get('/hello.txt', function(req, res) {
  return res.send('Hello World');
});
